"""Generate the consumer-facing data contract: `docs/data-contract.md`.

Third-party apps and agents that read `db.sqlite` directly need to know what
tables exist, what each column means, how fresh the data is, and where the
line is between "safe to read" and "must go through the daemon." This module
renders that as Markdown from manifests — no hand-maintained doc to drift
out of sync with the trackers/apps/sources that actually ship.

Two modes:

- **Installed** (default): walks `<root>/trackers`, `<root>/apps`,
  `<root>/sources` — what's actually on this machine. Useful for a user (or
  an agent) who wants a contract scoped to their own install.
- **Bundled** (`bundled=True`, CLI `--bundled`): walks the packaged templates
  under `personal_db.templates.{trackers,apps,sources}` directly via
  `importlib.resources`, ignoring `cfg` entirely — every tracker/app/source
  that ships with the package, whether or not this machine has it installed.
  This is the mode `docs/data-contract.md` is committed from (see
  `cli/dev_cmd.py` / `personal-db dev contract --bundled`).

`generate_contract(cfg)` is the single entry point; everything else here is
a rendering helper.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

from personal_db.core.apps import AppManifest, AppManifestError, load_app_manifest
from personal_db.core.config import Config
from personal_db.core.manifest import Manifest, ManifestError, load_manifest, platform_label
from personal_db.core.sources import SourceManifest, SourceManifestError, load_source_manifest

# Stated verbatim (see Phase 3 plan) so any consumer reading the generated
# doc gets the same three sentences regardless of which trackers are installed.
_CONSUMER_RULES = """\
- Read `db.sqlite` freely (read-only connection); never write to it.
- Mutations go through the daemon HTTP API (`/api/v1`, Bearer token from
  `<root>/state/daemon.token`).
- Table shapes are versioned per-tracker via `schema_version`; check
  `tracker_schema_versions`.
"""

# Hand-written: the core tables aren't declared by any manifest, so there's
# nothing to generate this section from. Keep it brief and update by hand
# when core/db.py's `_SCHEMA_SQL` or core/enrichment_queue.py's schema changes.
_CORE_TABLES_DOC = """\
These tables exist in every `db.sqlite` regardless of which trackers/apps are
installed (see `core/db.py` and `core/enrichment_queue.py`):

- **`people`** / **`people_aliases`** — resolved people and the raw
  identifiers (handles, emails, aliases) that map onto them.
- **`notes`** — an index over the user's notes directory (`path`, `title`,
  `created_at`, `body_excerpt`); the note bodies themselves live as files
  under `<root>/notes`, not in the DB.
- **`tracker_schema_versions`** — one row per tracker, the `schema_version`
  currently applied to its tables. Compare against a tracker's manifest
  `schema_version` before assuming its table shapes match this document.
- **`action_log`** — an audit trail of every action dispatched through the
  daemon (`surface`, `extension`, `action`, `params_json`, `result`),
  written before each action runs.
- **`enrichment_jobs`** (+ `enrichment_runs` / `enrichment_latest` /
  `enrichment_evidence`) — the generic background-enrichment queue: pending/
  running/completed jobs, their results, and cited evidence. Finance receipt
  enrichment is the first thing built on top of it.
"""

_HEADER_TEMPLATE = """\
# personal_db data contract

<!-- Auto-generated by `personal-db dev contract{bundled_flag}`. Do not edit
     by hand — regenerate with:
       personal-db dev contract --bundled --output docs/data-contract.md
-->

This document describes every {scope} tracker, app, and source: what tables
it puts in `db.sqlite`, what each column means, and how fresh/complete the
data is expected to be.

## Consumer rules

{rules}
## Core tables

{core_tables}
"""


def _iter_tracker_manifests(cfg: Config, *, bundled: bool) -> list[tuple[str, Path, Manifest]]:
    """Yield (name, tracker_dir, manifest) for every tracker in scope, sorted
    by name. Skips a tracker directory whose manifest fails to parse rather
    than aborting the whole contract (a hand-edited or in-progress tracker
    shouldn't block everyone else's docs)."""
    if bundled:
        root = resources.files("personal_db.templates.trackers")
        with resources.as_file(root) as root_path:
            return _load_tracker_manifests(root_path)
    if not cfg.trackers_dir.exists():
        return []
    return _load_tracker_manifests(cfg.trackers_dir)


def _load_tracker_manifests(root: Path) -> list[tuple[str, Path, Manifest]]:
    out: list[tuple[str, Path, Manifest]] = []
    for entry in sorted(root.iterdir(), key=lambda p: p.name):
        manifest_path = entry / "manifest.yaml"
        if not entry.is_dir() or not manifest_path.is_file():
            continue
        try:
            manifest = load_manifest(manifest_path)
        except ManifestError:
            continue
        out.append((entry.name, entry, manifest))
    return out


def _iter_app_manifests(cfg: Config, *, bundled: bool) -> list[tuple[str, AppManifest]]:
    if bundled:
        root = resources.files("personal_db.templates.apps")
        with resources.as_file(root) as root_path:
            return _load_app_manifests(root_path)
    if not cfg.apps_dir.exists():
        return []
    return _load_app_manifests(cfg.apps_dir)


def _load_app_manifests(root: Path) -> list[tuple[str, AppManifest]]:
    out: list[tuple[str, AppManifest]] = []
    for entry in sorted(root.iterdir(), key=lambda p: p.name):
        manifest_path = entry / "app.yaml"
        if not entry.is_dir() or not manifest_path.is_file():
            continue
        try:
            manifest = load_app_manifest(manifest_path)
        except AppManifestError:
            continue
        out.append((entry.name, manifest))
    return out


def _iter_source_manifests(cfg: Config, *, bundled: bool) -> list[tuple[str, SourceManifest]]:
    if bundled:
        root = resources.files("personal_db.templates.sources")
        with resources.as_file(root) as root_path:
            return _load_source_manifests(root_path)
    if not cfg.sources_dir.exists():
        return []
    return _load_source_manifests(cfg.sources_dir)


def _load_source_manifests(root: Path) -> list[tuple[str, SourceManifest]]:
    out: list[tuple[str, SourceManifest]] = []
    for entry in sorted(root.iterdir(), key=lambda p: p.name):
        manifest_path = entry / "source.yaml"
        if not entry.is_dir() or not manifest_path.is_file():
            continue
        try:
            manifest = load_source_manifest(manifest_path)
        except SourceManifestError:
            continue
        out.append((entry.name, manifest))
    return out


def _platform_caveat(platform: tuple[str, ...] | list[str] | None) -> str | None:
    if not platform:
        return None
    names = " or ".join(platform_label(p) for p in platform)
    return f"platform: {names} only"


def _render_tracker(name: str, manifest: Manifest) -> str:
    lines = [f"### `{name}`", "", manifest.description or "_(no description)_", ""]
    meta = [
        f"- **permission_type**: `{manifest.permission_type}`",
        f"- **schema_version**: `{manifest.schema_version}`",
    ]
    caveat = _platform_caveat(manifest.platform)
    if caveat:
        meta.append(f"- **{caveat}**")
    if manifest.local_only:
        meta.append(
            "- **local_only**: this tracker reads from local files/apps that don't survive a "
            "reinstall — expect a data horizon (no rows before the first successful sync on this "
            "machine) rather than a complete history."
        )
    if manifest.related_entities:
        meta.append(f"- **related_entities**: {', '.join(manifest.related_entities)}")
    lines.extend(meta)
    lines.append("")
    for table_name, table in sorted(manifest.schema.tables.items()):
        lines.append(f"#### Table `{table_name}`")
        lines.append("")
        lines.append("| column | type | semantic |")
        lines.append("|---|---|---|")
        for col_name, col in table.columns.items():
            lines.append(f"| `{col_name}` | `{col.type}` | {col.semantic} |")
        lines.append("")
    lines.append(f"- **time_column**: `{manifest.time_column}`")
    lines.append(f"- **granularity**: `{manifest.granularity}`")
    lines.append("")
    return "\n".join(lines)


def _render_app(name: str, manifest: AppManifest) -> str:
    lines = [f"### `{name}`", "", manifest.description or "_(no description)_", ""]
    caveat = _platform_caveat(manifest.platform)
    if caveat:
        lines.append(f"- **{caveat}**")
    if manifest.reads.tables or manifest.reads.models:
        reads = []
        if manifest.reads.tables:
            reads.append(f"tables: {', '.join(manifest.reads.tables)}")
        if manifest.reads.models:
            reads.append(f"models: {', '.join(manifest.reads.models)}")
        lines.append(f"- **reads**: {'; '.join(reads)}")
    if manifest.writes.tables or manifest.writes.actions:
        writes = []
        if manifest.writes.tables:
            writes.append(f"tables: {', '.join(manifest.writes.tables)}")
        if manifest.writes.actions:
            writes.append(f"actions: {', '.join(manifest.writes.actions)}")
        lines.append(f"- **writes** (via `/api/v1/apps/{name}/actions/<action>`): {'; '.join(writes)}")
    lines.append(f"- **pages**: {', '.join(p.slug for p in manifest.pages)}")
    lines.append("")
    return "\n".join(lines)


def _render_source(name: str, manifest: SourceManifest) -> str:
    lines = [f"### `{name}`", "", manifest.description or "_(no description)_", ""]
    lines.append(f"- **provider**: `{manifest.provider}`")
    caveat = _platform_caveat(manifest.platform)
    if caveat:
        lines.append(f"- **{caveat}**")
    if manifest.capabilities:
        lines.append(f"- **capabilities**: {', '.join(manifest.capabilities)}")
    lines.append("")
    return "\n".join(lines)


def generate_contract(cfg: Config, *, bundled: bool = False) -> str:
    """Render the Markdown data contract.

    `bundled=False` (default): describes what's installed under `cfg.root`.
    `bundled=True`: describes every bundled template regardless of `cfg` —
    this is the mode `docs/data-contract.md` is committed from.
    """
    scope = "bundled" if bundled else "installed"
    bundled_flag = " --bundled" if bundled else ""
    parts = [
        _HEADER_TEMPLATE.format(
            bundled_flag=bundled_flag,
            scope=scope,
            rules=_CONSUMER_RULES,
            core_tables=_CORE_TABLES_DOC,
        )
    ]

    trackers = _iter_tracker_manifests(cfg, bundled=bundled)
    parts.append(f"## Trackers ({len(trackers)})\n")
    if not trackers:
        parts.append("_(none installed)_\n")
    for name, _tracker_dir, manifest in trackers:
        parts.append(_render_tracker(name, manifest))

    apps = _iter_app_manifests(cfg, bundled=bundled)
    parts.append(f"## Apps ({len(apps)})\n")
    if not apps:
        parts.append("_(none installed)_\n")
    for name, manifest in apps:
        parts.append(_render_app(name, manifest))

    sources = _iter_source_manifests(cfg, bundled=bundled)
    parts.append(f"## Sources ({len(sources)})\n")
    if not sources:
        parts.append("_(none installed)_\n")
    for name, manifest in sources:
        parts.append(_render_source(name, manifest))

    return "\n".join(parts).rstrip() + "\n"
